version: 2
project_name: "gitlab-backup"
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - id: gitlab-backup
    binary: gitlab-backup
    main: ./cmd/gitlab-backup
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
  - id: gitlab-restore
    binary: gitlab-restore
    main: ./cmd/gitlab-restore
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"

archives:
  - id: gitlab-backup-archive
    builds:
      - gitlab-backup
    name_template: 'gitlab-backup_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    formats: ["binary"]
  - id: gitlab-restore-archive
    builds:
      - gitlab-restore
    name_template: 'gitlab-restore_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    formats: ["binary"]

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  # https://goreleaser.com/customization/docker/
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/sgaunet/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/sgaunet/{{ .ProjectName }}:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files:
    - resources

  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/sgaunet/{{ .ProjectName }}:{{ .Version }}-arm64v8"
      - "ghcr.io/sgaunet/{{ .ProjectName }}:latest-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files:
    - resources

  - use: buildx
    goos: linux
    goarch: arm
    goarm: "6"
    image_templates:
      - "ghcr.io/sgaunet/{{ .ProjectName }}:{{ .Version }}-armv6"
      - "ghcr.io/sgaunet/{{ .ProjectName }}:latest-armv6"
    build_flag_templates:
      - "--platform=linux/arm/v6"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files:
    - resources

  - use: buildx
    goos: linux
    goarch: arm
    goarm: "7"
    image_templates:
      - "ghcr.io/sgaunet/{{ .ProjectName }}:{{ .Version }}-armv7"
      - "ghcr.io/sgaunet/{{ .ProjectName }}:latest-armv7"
    build_flag_templates:
      - "--platform=linux/arm/v7"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files:
    - resources

docker_manifests:
  # https://goreleaser.com/customization/docker_manifest/
  - name_template: ghcr.io/sgaunet/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/sgaunet/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/sgaunet/{{ .ProjectName }}:{{ .Version }}-arm64v8
      - ghcr.io/sgaunet/{{ .ProjectName }}:{{ .Version }}-armv6
      - ghcr.io/sgaunet/{{ .ProjectName }}:{{ .Version }}-armv7
  - name_template: ghcr.io/sgaunet/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/sgaunet/{{ .ProjectName }}:latest-amd64
      - ghcr.io/sgaunet/{{ .ProjectName }}:latest-arm64v8
      - ghcr.io/sgaunet/{{ .ProjectName }}:latest-armv6
      - ghcr.io/sgaunet/{{ .ProjectName }}:latest-armv7


brews:
  - ids:
      - gitlab-backup-archive
    homepage: 'https://github.com/sgaunet/gitlab-backup'
    description: 'A tool for backing up GitLab projects'
    directory: Formula
    commit_author:
      name: sgaunet
      email: 1552102+sgaunet@users.noreply.github.com
    repository:
      owner: sgaunet
      name: homebrew-tools
      # Token with 'repo' scope is required for pushing to a different repository
      token: '{{ .Env.HOMEBREW_TAP_TOKEN }}'
    url_template: 'https://github.com/sgaunet/gitlab-backup/releases/download/{{ .Tag }}/{{ .ArtifactName }}'
    install: |
      bin.install "{{ .ArtifactName }}" => "gitlab-backup"
    test: |
      system "#{bin}/gitlab-backup", "--help"
  - ids:
      - gitlab-restore-archive
    homepage: 'https://github.com/sgaunet/gitlab-backup'
    description: 'A tool for restoring GitLab projects from backups'
    directory: Formula
    commit_author:
      name: sgaunet
      email: 1552102+sgaunet@users.noreply.github.com
    repository:
      owner: sgaunet
      name: homebrew-tools
      # Token with 'repo' scope is required for pushing to a different repository
      token: '{{ .Env.HOMEBREW_TAP_TOKEN }}'
    url_template: 'https://github.com/sgaunet/gitlab-backup/releases/download/{{ .Tag }}/{{ .ArtifactName }}'
    install: |
      bin.install "{{ .ArtifactName }}" => "gitlab-restore"
    test: |
      system "#{bin}/gitlab-restore", "--help"
