# https://taskfile.dev
version: '3'
vars:
  BINFILE: gitlab-backup

tasks:
  default:
    cmds:
      - CGO_ENABLED=0 go build cmd/*.go

  image:
    deps:
      - default
    cmds:
      - docker build --no-cache --build-arg VERSION=development . -t sgaunet/gitlab-backup:latest
      - docker push sgaunet/gitlab-backup:latest

  doc:
    cmds:
      - echo http://localhost:6060 
      - godoc -http=:6060

  snapshot:
    cmds:
      - GITLAB_TOKEN="" goreleaser --rm-dist --snapshot
    
  release:
    cmds:
      - GITLAB_TOKEN="" goreleaser --rm-dist
    