# https://taskfile.dev
version: '3'
vars:
  BINFILE: gitlab-backup

tasks:
  default:
    desc: "List tasks"
    cmds:
      - task -a

  build:
    desc: "Build the binary"
    cmds:
      - CGO_ENABLED=0 go build cmd/*.go

  image:
    desc: "Build/push the docker image"
    deps:
      - build
    cmds:
      - docker build --no-cache --build-arg VERSION=development . -t ghcr.io/sgaunet/gitlab-backup:latest
      - docker push ghcr.io/sgaunet/gitlab-backup:latest

  doc:
    desc: "Start godoc server"
    cmds:
      - echo http://localhost:6060 
      - godoc -http=:6060

  snapshot:
    desc: "Create a snapshot release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot
    
  release:
    desc: "Create a release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --skip validate
    