version: '3.7'
services:
  minio:
    image: minio/minio:RELEASE.2023-04-13T03-08-07Z.fips
    ports:
        - 9090:9000
        - 8080:8080
    environment: 
        - MINIO_ROOT_USER=minioadminn
        - MINIO_ROOT_PASSWORD=minioadminn
        - MINIO_BUCKET=tests
    volumes:
        - ./data-minio:/export
    command: server /export --console-address 0.0.0.0:8080

  createbucket:
    image: minio/mc
    environment:
      - MINIO_ROOT_USER=minioadminn
      - MINIO_ROOT_PASSWORD=minioadminn
      - MINIO_BUCKET=tests
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minioadminn minioadminn;
      /usr/bin/mc mb myminio/tests;
      /usr/bin/mc anonymous set private myminio/tests;
      exit 0;
      "
