name: snapshot

on:
  push:

permissions:
  contents: read

jobs:
  goreleaser-snapshot:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.24'
      - name: Install task
        uses: jaxxstorm/action-install-gh-release@v2.1.0
        with:
          repo: go-task/task
          cache: true
          # tag: 
      - name: Install goreleaser
        uses: jaxxstorm/action-install-gh-release@v2.1.0
        with:
          repo: goreleaser/goreleaser
          cache: true
          # tag: 

      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create snapshot release
        shell: /usr/bin/bash {0}
        run: |
          task snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
